### ISSUE TITLE
outproxy

### ISSUE THREAD

**Issue by artenax** [altonen/emissary#104]
Is there any way to configure http outproxy?

**Comment by altonen** [comment]
Currently there is no outproxy support

**Comment by altonen** [comment]
Outproxy support was implemented in #118 

Example config for HTTP proxy:
```toml
[http-proxy]
port = 4444
host = "127.0.0.1"
outproxy = "exit.stormycloud.i2p"
```
